// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_INjni0WgaDGPBX1HfY5Hf-3FuGq9hs',
    appId: '1:767872125298:web:7d6c130d63acd35ba3f5eb',
    messagingSenderId: '767872125298',
    projectId: 'mydhamma-8',
    authDomain: 'mydhamma-8.firebaseapp.com',
    databaseURL: 'https://mydhamma-8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mydhamma-8.firebasestorage.app',
    measurementId: 'G-6ZM6DC80YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvbF5QXYpyXBXFVjoZh_dm4w8wYj5Hk0',
    appId: '1:767872125298:android:04399e37f9f3f2f4a3f5eb',
    messagingSenderId: '767872125298',
    projectId: 'mydhamma-8',
    databaseURL: 'https://mydhamma-8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mydhamma-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV15ELsOrzeaXgplAfCyaROA6gSt5VUbY',
    appId: '1:767872125298:ios:0e50fa5ec4be5fdba3f5eb',
    messagingSenderId: '767872125298',
    projectId: 'mydhamma-8',
    databaseURL: 'https://mydhamma-8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mydhamma-8.firebasestorage.app',
    iosBundleId: 'id.aluska.tipitaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV15ELsOrzeaXgplAfCyaROA6gSt5VUbY',
    appId: '1:767872125298:ios:0e50fa5ec4be5fdba3f5eb',
    messagingSenderId: '767872125298',
    projectId: 'mydhamma-8',
    databaseURL: 'https://mydhamma-8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mydhamma-8.firebasestorage.app',
    iosBundleId: 'id.aluska.tipitaka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd_INjni0WgaDGPBX1HfY5Hf-3FuGq9hs',
    appId: '1:767872125298:web:e5afb587784fe4b9a3f5eb',
    messagingSenderId: '767872125298',
    projectId: 'mydhamma-8',
    authDomain: 'mydhamma-8.firebaseapp.com',
    databaseURL: 'https://mydhamma-8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mydhamma-8.firebasestorage.app',
    measurementId: 'G-K98X1E3TZ0',
  );
}
